### ISSUE TITLE
compile error (initializer and unknown type)

### ISSUE THREAD

**Issue by AnimaMachina** [SveSop/nvidia-libs#21]
I'm trying to compile nvidia-libs (using wine-staging 9.10).

I have some error I didn't find to fix nor to understand well.

```
FAILED: dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o
...
nvidia-libs/dlls/nvcuda/internal.c:58:15: error: initializer element is not computable at load time
   58 |       0, 0, { (DWORD_PTR)(__FILE__ ": tls_callback_section") }
      |               ^
nvidia-libs/dlls/nvcuda/internal.c:58:15: note: (near initialization for ‘critsect_debug.Spare[0]’)
```

and letter :

```
FAILED: dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o
...
In file included from /opt/wine-staging/include/wine/windows/winscard.h:22,
                 from /opt/wine-staging/include/wine/windows/windows.h:68,
                 from /opt/wine-staging/include/wine/windows/rpc.h:22,
                 from /opt/wine-staging/include/wine/windows/objbase.h:19,
                 from /opt/wine-staging/include/wine/windows/d3d9.h:30,
                 from nvidia-libs/dlls/nvcuda/nvcuda.c:37:
/opt/wine-staging/include/wine/windows/wtypes.h:370:5: error: unknown type name ‘byte’
  370 |     byte abData[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:376:5: error: unknown type name ‘byte’
  376 |     byte abData[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:387:5: error: unknown type name ‘byte’
  387 |     byte *pData;
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:399:5: error: unknown type name ‘hyper’
  399 |     hyper *pData;
      |     ^~~~~
/opt/wine-staging/include/wine/windows/wtypes.h:419:5: error: unknown type name ‘byte’
  419 |     byte data[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:435:5: error: unknown type name ‘byte’
  435 |     byte data[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:463:5: error: unknown type name ‘byte’
  463 |     byte data[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:476:5: error: unknown type name ‘byte’
  476 |     byte data[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:486:5: error: unknown type name ‘byte’
  486 |     byte pBuffer[1];
      |     ^~~~
/opt/wine-staging/include/wine/windows/wtypes.h:499:5: error: unknown type name ‘byte’
  499 |     byte data[1];
      |     ^~~~
```

I'm using packages wine-staging and wine-staging-dev versions 9.10~focal-1

**Comment by SveSop** [comment]
Winegcc should only be a layer on top of gcc, so you could possibly post the result of `winegcc --version`

`focal` indicates you are using Ubuntu 20.04, but i have not tried to compile on that for ages, and do not really have a 20.04 system running atm sadly. It does compile on Ubuntu 22.04 and Arch.

If all else fails and you just want the most recent binaries, you can always download the pre-compiled artifacts package from:
[https://github.com/SveSop/nvidia-libs/actions](https://github.com/SveSop/nvidia-libs/actions)

**Comment by AnimaMachina** [comment]
Yes I'm using an ubuntu derived distro, and not the last major one (not derived on ubuntu 22.04/jammy but on 20.04/focal). (I would like to compile, because the released libs don't run on my system, asking needing a GLIBC higher than mine)

My gcc and winegcc are 9.4.0 version.
I just tested on a vm with the next major version of my linux, which use gcc and winegcc 11.4. It compile fine !

=>
It's seems you are right it's a problem of version of gcc/winegcc so a version of linux (I don't think we can force winegcc using gcc/g++ 10 or 11 ?).

I also tested on my system winegcc 9.4.0, based on other forum posts, if I can force the c/c++ standard used (tried  changing meson.build parameter, ninja build file parameter, ninja command parameter [cpp_std var and -std parameter], with c++14, c++17, c++2a) but it doesn't fix anything.

Perhaps you only need to add in requirements wingcc 11 (or 10 ?) ?
And me I must upgrade my system.

Thanks for your infos, and for your job.

**Comment by SveSop** [comment]
If you are able to use PPA's, you might get to install GCC-11 on your distro. 
[https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test)
I am aware however that i think this "test" ppa is flagged to be deleted at some point, so i cannot verify that it actually work.

I also have a backport for mingw on my own ppa that i used to use before upgrading to 22.04: [https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport)

There are probably others more up-to-date than this, as i have not really updated anything for Focal for a long time.

As to winegcc, afaik winegcc is just a "wrapper" around your system gcc, so it should basically mean that `gcc --version` is the same as `winegcc --version`.

It might be that the issue is not too hard to "fix", so i will take a closer look at the requirements - although i think it is time to upgrade, and then to 24.04 distro even tho i am "not there yet" myself 😄

**Comment by SveSop** [comment]
@AnimaMachina 
Oki.. so i managed to compile this on Ubuntu 20.04 with some updated settings. So i will try to explain to the best of my knowledge.
First you need to make sure you have all Ubuntu repositories enabled (eg. Backports/updates).
Then you can install or make sure this is installed: (PS. use the WineHQ provided packages for wine, but i assume you already do this).

```
build-essential
mingw-w64
gcc-10 g++-10 gcc-10-multilib g++-10-multilib
meson ninja-build
```
Make sure the "devel" package for wine is installed. That is if you are running winehq-staging, it is called `wine-staging-dev`

Then you set the default compiler to be gcc-10 like this:
```
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
```
Then select the `Posix` alternative when running these commands:
```
update-alternatives --config x86_64-w64-mingw32-gcc
update-alternatives --config x86_64-w64-mingw32-g++
update-alternatives --config i686-w64-mingw32-gcc
update-alternatives --config i686-w64-mingw32-g++
```
Check that gcc is actually gcc-10 by running `gcc --version` - and even `winegcc --version`

If all is good so far, that is USUALLY the requirements for compiling this, but due to Ubuntu 20.04 not having updated packages anymore, you need to add two PPA's :
[https://launchpad.net/~pipewire-debian/+archive/ubuntu/meson-ninja)](https://launchpad.net/~pipewire-debian/+archive/ubuntu/meson-ninja)
```
sudo add-apt-repository ppa:pipewire-debian/meson-ninja
sudo apt update && sudo apt upgrade
```
And my old personal one for mingw-w64:
[https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport)](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport)
```
sudo add-apt-repository ppa:cybermax-dexter/mingw-w64-backport
sudo apt update && sudo apt upgrade
```

This atleast for me seemed to compile the binaries using the `package-release.sh` script 😄  Let me know if it worked for you!

**Comment by AnimaMachina** [comment]
Yes it works.
My missing parts was the meson/ninja updgrade and mingw backport.

Thanks for your infos.
